version: '3.7'

services:
  babble:
    container_name: babble
    image: ndc212/babble:0.0.3
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:443
    environment:
      - CHOKIDAR_USEPOLLING=true